export type LandingLang = 'en' | 'ar';

export function normalizeLandingLang(raw: string | undefined): LandingLang {
  return String(raw || 'en').toLowerCase().startsWith('ar') ? 'ar' : 'en';
}

const en = {
  meta: {
    title: 'Tik — Manage Teams, Tickets & Attendance in One Place',
    jsonLdDescription:
      'All-in-one internal operations platform — ticketing, messaging, attendance.',
  },
  nav: {
    features: 'Features',
    platform: 'Platform',
    pricing: 'Pricing',
    reviews: 'Reviews',
    getStarted: 'Get Started',
    signIn: 'Sign in',
    viewPlans: 'View Plans',
    getStartedFree: 'Get Started Free',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },
  hero: {
    badge: 'Now available — Web & Mobile',
    titleBefore: 'Your team.',
    titleAccent: 'One place.',
    titleAfter: ' Zero chaos.',
    description:
      'Tik replaces WhatsApp groups, paper attendance, and scattered tasks with structured ticketing, real team messaging, and GPS-ready attendance — built for SMEs across Egypt and MENA.',
    ctaPrimary: 'Get Started Free →',
    ctaSecondary: 'See How It Works',
    stat1a: '3-in-1',
    stat1b: 'Modules',
    stat2a: '14 days',
    stat2b: 'Free trial',
    stat3a: '~20 min',
    stat3b: 'Setup time',
  },
  phoneMockup: {
    myTickets: 'My Tickets',
    ticketRows: [
      {
        id: '#1842',
        status: 'OPEN',
        title: 'Client onboarding checklist',
        variant: 'open' as const,
      },
      {
        id: '#1840',
        status: 'REVIEW',
        title: 'Q4 logistics report',
        variant: 'review' as const,
      },
      {
        id: '#1838',
        status: 'DONE',
        title: 'Payroll export — Oct',
        variant: 'done' as const,
      },
    ],
    weekTitle: 'This week',
    statResolvedLabel: 'Resolved',
    statResolvedValue: '24',
    statOverdueLabel: 'Overdue',
    statOverdueValue: '3',
    statReviewLabel: 'In review',
    statReviewValue: '7',
    checkInsTitle: "Today's check-ins",
    checkIns: [
      { text: 'Ahmed — 9:02 AM ✓', warning: false },
      { text: 'Sara — 9:15 AM ✓', warning: false },
      { text: 'Karim — Late', warning: true },
    ],
  },
  problem: {
    sectionLabel: 'The Problem',
    title: 'Your company runs on',
    titleAccent: '3 broken systems.',
    description:
      "Spreadsheets, group chats, and paper sign-ins don't scale. Tik unifies operations so everyone knows what to do, who owns it, and who showed up.",
    bullets: [
      'Work lives in WhatsApp — requests get lost in noise.',
      'Attendance is manual, error-prone, and hard to audit.',
      'Managers are blind — no live view of workload or presence.',
    ],
    beforeAfter: 'Before / After',
    beforeItems: [
      'Tasks buried in WhatsApp',
      'Paper attendance sheets',
      '"Did anyone see my message?"',
      'Manual Excel exports',
    ],
    afterItems: [
      'Tickets created, assigned, and tracked',
      'GPS check-in with audit trail',
      'Structured channels + pinned updates',
      'Live manager dashboard',
    ],
  },
  features: {
    sectionTitle: 'Everything your team needs.',
    sectionAccent: 'Nothing extra.',
    tickets: {
      title: 'Project Tickets',
      description:
        'Turn requests into accountable work — with history, owners, and deadlines.',
      bullets: [
        'Create tickets per project or department',
        'Assign owners & set due dates',
        'Automatic overdue alerts to managers',
        'Priority levels & SLA timers',
        'Full activity log per ticket',
        'Manager dashboard — live status overview',
        'email notification',
        'multi ticket hanler',
        'cc in ticket',
      ],
    },
    messaging: {
      title: 'Team Messaging',
      description: 'Structured chat that connects to real work — not another noisy group.',
      bullets: [
        'Direct & group messaging',
        'Channels per project or department',
        'File sharing with organized storage',
        'recorded messages',
        'replay in thread',
        'Multi-company workspace switcher',
        'project group auto chat'
      ],
    },
    attendance: {
      title: 'Attendance Tracking',
      description:
        'Know who is in — with policies, approvals, and exports finance can use.',
      bullets: [
        'GPS-verified check-in & check-out',
        'Shift scheduling & management',    
        'Monthly payroll-ready export',
        'Multi-location & field employee support',
        'finished tasks report',
        'admin edit attendance',
        'multi check in and out per day'
      ],
    },
    digestTitle: 'The Daily Digest — every morning at 9am',
    digestDescription:
      'Managers get a single summary: overdue tickets, attendance exceptions, and must-read announcements — without opening five different apps.',
    previewLabel: 'Preview',
    previewLines: [
      '3 overdue tickets',
    
      '1 pinned announcement',
    ],
  },
  platform: {
    sectionLabel: 'Platform',
    title: 'Web & Mobile.',
    titleAccent: 'Everywhere your team is.',
    description:
      'The same workspace on desktop and phone — so field teams, night shifts, and office staff stay aligned in real time.',
    webApp: 'Web App',
    iosApp: 'iOS App',
    androidApp: 'Android App',
    bullets: [
      'Real-time sync across devices',
      'Push notifications for tickets & messages',
      'GPS check-in for distributed teams',
      'Tickets email notification',
 
    ],
  },
  pricing: {
    title: 'Simple pricing.',
    titleAccent: 'Serious value.',
    subtitle: 'Plans sync with your live catalog from the API when online.',
    freeLabel: 'Free',
    perWorkspace: '/ workspace',
    seatMo: ' / mo',
    perMonth: '/ month',
    starterSubtitleFallback: 'For up to 15 seats',
    growthSubtitleFallback: 'Min 10 seats · full operations suite',
    businessSubtitleFallback: '200+ seats · enterprise options',
    ctaStarter: 'Get Started Free →',
    ctaGrowth: 'Start 14-Day Free Trial →',
    ctaBusiness: 'Contact Sales →',
    ctaEnterprise: 'Contact Us →',
    enterpriseTitle: 'Enterprise',
    enterpriseSubtitleFallback: '30+ seats · custom onboarding & enterprise support',
    enterprisePriceLabel: 'Custom',
    contactFormTitle: 'Contact us for enterprise',
    contactFormSubtitle: 'Tell us about your team and we will reach out quickly.',
    contactName: 'Full name',
    contactEmail: 'Work email',
    contactCompany: 'Company',
    contactPhone: 'Phone (optional)',
    contactSeats: 'Team size',
    contactMessage: 'What do you need?',
    contactSubmit: 'Send request',
    contactSending: 'Sending...',
    contactSuccess: 'Thanks! Your request was sent. We will contact you shortly.',
    contactError: 'Could not send your request. Please try again.',
    contactRequired: 'Please fill all required fields.',
    badgePopular: '⭐ MOST POPULAR',
    starterMissing: ['Multiple admins', 'GPS check-in', 'Payroll-ready export'],
    footnote:
      "All prices in EGP. Fawry, Vodafone Cash, bank transfer, and credit cards accepted. 14-day free trial, no credit card required. Bundle details follow your company's live plan catalog in the product.",
  },
  signup: {
    title: 'Start your 14-day free trial',
    subtitle: 'No credit card required. Set up your company in under 20 minutes.',
    ownerName: 'Owner name',
    companyName: 'Company name',
    workEmail: 'Work email',
    password: 'Password',
    phOwner: 'John Doe',
    phCompany: 'Acme Logistics',
    phEmail: 'you@company.com',
    phPassword: 'At least 8 characters',
    submit: 'Create Free Account →',
    legal: 'By signing up, you agree to our Terms of Service and Privacy Policy.',
    errOwner: 'Owner name is required',
    errCompany: 'Company name is required',
    errEmail: 'Email is required',
    errEmailInvalid: 'Enter a valid email',
    errPassword: 'Password is required',
    errPasswordLen: 'Minimum 8 characters',
  },
  testimonials: {
    title: 'Teams that switched',
    titleAccent: 'to Tik.',
    cards: [
      {
        initials: 'KM',
        name: 'Khaled Mansour',
        role: 'Operations Manager, Cairo',
        quote:
          'We were running everything on WhatsApp groups. Tik gave us structure overnight. Now I can open one screen and know exactly what my team is working on and who checked in.',
      },
      {
        initials: 'NH',
        name: 'Nour Hassan',
        role: 'HR Director, Alexandria',
        quote:
          'The attendance export alone saved our HR team 3 hours every month. No more manual Excel sheets. It just works, and my accountant loves the payroll-ready format.',
      },
      {
        initials: 'SA',
        name: 'Sara Abdelhady',
        role: 'CEO, Digital Agency',
        quote:
          'As a growing agency with 40 people across two offices, we needed one place. Tik was set up in a single afternoon. The team adopted it immediately.',
      },
    ],
  },
  cta: {
    title: 'Ready to stop the',
    titleAccent: 'chaos?',
    description:
      'Join Egyptian and MENA teams who replaced scattered tools with one operations hub — tickets, chat, and attendance in sync.',
    primary: 'Start Free Trial — No Card Needed →',
    secondary: 'View Pricing',
    footnote: '14-day free trial · All 3 modules included · Setup in 20 minutes · Web & Mobile',
  },
  footer: {
    blurb:
      'Tickets, team chat, and attendance — one platform for Egyptian and MENA SMEs. Replace scattered tools with one source of truth.',
    product: 'Product',
    company: 'Company',
    support: 'Support',
    linkFeatures: 'Features',
    linkPricing: 'Pricing',
    linkMobile: 'Mobile App',
    linkChangelog: 'Changelog',
    linkAbout: 'About',
    linkBlog: 'Blog',
    linkCareers: 'Careers',
    linkContact: 'Contact',
    linkHelp: 'Help Center',
    linkOnboarding: 'Onboarding Guide',
    linkStatus: 'System Status',
    linkApi: 'API Docs',
    rights: 'All rights reserved.',
    contactEmail: 'tik@absai.dev',
    contactPhone: '01099112703',
    contactAddress: 'القاهرة التجمع الاول وبنفسج 11 و فيلا 55',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    cookies: 'Cookie Policy',
  },
  trusted: {
    prefix: 'Trusted by teams in',
    items: [
      'Marketing Agencies',
      'IT Companies',
      'Logistics Firms',
      'Private Clinics',
      'Law Firms',
      'Real Estate',
      'E-commerce',
      'Construction',
      'Factories',
      'Hospitals',
    ],
  },
} as const;

export type LandingMessages = typeof en;

const ar: LandingMessages = {
  meta: {
    title: 'Tik — إدارة الفرق والتذاكر والحضور في مكان واحد',
    jsonLdDescription:
      'منصة عمليات داخلية شاملة — تذاكر، رسائل، وحضور.',
  },
  nav: {
    features: 'الميزات',
    platform: 'المنصة',
    pricing: 'الأسعار',
    reviews: 'آراء العملاء',
    getStarted: 'ابدأ الآن',
    signIn: 'تسجيل الدخول',
    viewPlans: 'عرض الباقات',
    getStartedFree: 'ابدأ مجانًا',
    openMenu: 'فتح القائمة',
    closeMenu: 'إغلاق القائمة',
  },
  hero: {
    badge: 'متاح الآن — ويب وموبايل',
    titleBefore: 'فريقك.',
    titleAccent: 'مكان واحد.',
    titleAfter: ' بلا فوضى.',
    description:
      'Tik يستبدل مجموعات واتساب وحضور الورق والمهام المتناثرة بتذاكر منظمة، ومحادثات فعلية للفريق، وحضور جاهز للـ GPS — مصمّم للشركات الصغيرة والمتوسطة في مصر ومنطقة الشرق الأوسط وشمال أفريقيا.',
    ctaPrimary: 'ابدأ مجانًا ←',
    ctaSecondary: 'شاهد كيف يعمل',
    stat1a: '٣ في ١',
    stat1b: 'وحدات',
    stat2a: '١٤ يومًا',
    stat2b: 'تجربة مجانية',
    stat3a: '~٢٠ دقيقة',
    stat3b: 'وقت الإعداد',
  },
  phoneMockup: {
    myTickets: 'تذاكري',
    ticketRows: [
      {
        id: '#1842',
        status: 'مفتوحة',
        title: 'قائمة مراجعة إدماج العميل',
        variant: 'open' as const,
      },
      {
        id: '#1840',
        status: 'مراجعة',
        title: 'تقرير لوجستيات الربع الرابع',
        variant: 'review' as const,
      },
      {
        id: '#1838',
        status: 'منجزة',
        title: 'تصدير الرواتب — أكتوبر',
        variant: 'done' as const,
      },
    ],
    weekTitle: 'هذا الأسبوع',
    statResolvedLabel: 'تم الحل',
    statResolvedValue: '24',
    statOverdueLabel: 'متأخرة',
    statOverdueValue: '3',
    statReviewLabel: 'قيد المراجعة',
    statReviewValue: '7',
    checkInsTitle: 'تسجيلات الحضور اليوم',
    checkIns: [
      { text: 'أحمد — ٩:٠٢ ص ✓', warning: false },
      { text: 'سارة — ٩:١٥ ص ✓', warning: false },
      { text: 'كريم — متأخر', warning: true },
    ],
  },
  problem: {
    sectionLabel: 'المشكلة',
    title: 'شركتك تعمل على',
    titleAccent: '٣ أنظمة مكسورة.',
    description:
      'جداول البيانات ومجموعات الدردشة وتوقيعات الورق لا تتوسع. Tik يوحّد العمليات حتى يعرف الجميع ماذا يفعلون، من المسؤول، ومن حضر.',
    bullets: [
      'العمل يدور في واتساب — الطلبات تضيع بين الرسائل.',
      'الحضور يدوي، عرضة للخطأ، وصعب التدقيق.',
      'المدراء بلا رؤية حية لعبء العمل أو التواجد.',
    ],
    beforeAfter: 'قبل / بعد',
    beforeItems: [
      'مهام مدفونة في واتساب',
      'أوراق حضور يدوية',
      '«هل رأى أحد رسالتي؟»',
      'تصدير Excel يدوي',
    ],
    afterItems: [
      'تذاكر تُنشأ وتُعيَّن وتُتتبَّع',
      'تسجيل دخول GPS مع أثر تدقيق',
      'قنوات منظمة + تحديثات مثبتة',
      'لوحة تحكم للمدير لحظيًا',
    ],
  },
  features: {
    sectionTitle: 'كل ما يحتاجه فريقك.',
    sectionAccent: 'دون زيادة.',
    tickets: {
      title: 'تذاكر المشاريع',
      description: 'حوّل الطلبات إلى عمل مسؤول — مع السجل والمالكين والمواعيد النهائية.',
      bullets: [
        'إنشاء تذاكر لكل مشروع أو قسم',
        'تعيين مسؤولين ومواعيد نهائية',
        'تنبيهات تأخير تلقائية للمدراء',
        'أولويات ومؤقتات SLA',
        'سجل نشاط كامل لكل تذكرة',
        'لوحة تحكم للمدير — نظرة حية على الحالة',
        'إشعارات البريد الإلكتروني',
        'معالجة متعددة للتذاكر',
        'إضافة CC داخل التذكرة',
      ],
    },
    messaging: {
      title: 'مراسلة الفريق',
      description: 'دردشة منظمة ترتبط بالعمل الفعلي — وليست مجموعة ضوضاء أخرى.',
      bullets: [
        'رسائل مباشرة وجماعية',
        'قنوات لكل مشروع أو قسم',
        'مشاركة ملفات وتخزين منظم',
        'رسائل صوتية مسجّلة',
        'الرد داخل سلسلة المحادثة',
        'تبديل مساحة عمل متعددة الشركات',
        'إنشاء دردشة جماعية تلقائيًا لكل مشروع',
      ],
    },
    attendance: {
      title: 'تتبع الحضور',
      description: 'اعرف من موجود — بسياسات وموافقات وتصديرات يرضى عنها المالية.',
      bullets: [
        'تسجيل الحضور والانصراف مع التحقق عبر GPS',
        'جدولة وإدارة الورديات',
        'تصدير شهري جاهز للرواتب',
        'دعم المواقع المتعددة وموظفي الميدان',
        'تقرير المهام المنجزة',
        'تعديل الحضور من قبل المشرف',
        'تعدد تسجيل الحضور والانصراف خلال اليوم',
      ],
    },
    digestTitle: 'الملخص اليومي — كل صباح الساعة ٩',
    digestDescription:
      'يحصل المدراء على ملخص واحد: التذاكر المتأخرة، استثناءات الحضور، والإعلانات الواجب قراءتها — دون فتح خمس تطبيقات.',
    previewLabel: 'معاينة',
    previewLines: ['٣ تذاكر متأخرة', '٢ موظفين متأخرين', '١ إعلان مثبت'],
  },
  platform: {
    sectionLabel: 'المنصة',
    title: 'ويب وموبايل.',
    titleAccent: 'أينما كان فريقك.',
    description:
      'نفس مساحة العمل على سطح المكتب والهاتف — حتى الفرق الميدانية والورديات الليلية والموظفين في المكتب يبقون على توافق لحظي.',
    webApp: 'تطبيق الويب',
    iosApp: 'iOS',
    androidApp: 'أندرويد',
    bullets: [
      'مزامنة لحظية بين الأجهزة',
      'إشعارات فورية للتذاكر والرسائل',
      'تسجيل دخول GPS للفرق الموزعة',
      'إشعارات بريدية للتذاكر',
    ],
  },
  pricing: {
    title: 'تسعير بسيط.',
    titleAccent: 'قيمة حقيقية.',
    subtitle: 'تتزامن الباقات مع الكتالوج الحي من واجهة البرمجة عند الاتصال.',
    freeLabel: 'مجانًا',
    perWorkspace: '/ مساحة العمل',
    seatMo: '/ شهريًا',
    perMonth: '/ شهر',
    starterSubtitleFallback: 'حتى ١٥ مقعدًا',
    growthSubtitleFallback: '١٠ مقاعد كحد أدنى · مجموعة عمليات كاملة',
    businessSubtitleFallback: '٢٠٠+ مقعد · خيارات للمؤسسات',
    ctaStarter: 'ابدأ مجانًا ←',
    ctaGrowth: 'ابدأ تجربة ١٤ يومًا ←',
    ctaBusiness: 'تواصل مع المبيعات ←',
    ctaEnterprise: 'تواصل معنا ←',
    enterpriseTitle: 'المؤسسات',
    enterpriseSubtitleFallback: 'أكثر من ٣٠ مقعدًا · تهيئة مخصصة ودعم للمؤسسات',
    enterprisePriceLabel: 'حسب الطلب',
    contactFormTitle: 'تواصل معنا لخطة المؤسسات',
    contactFormSubtitle: 'شاركنا تفاصيل فريقك وسنتواصل معك بسرعة.',
    contactName: 'الاسم الكامل',
    contactEmail: 'بريد العمل',
    contactCompany: 'الشركة',
    contactPhone: 'الهاتف (اختياري)',
    contactSeats: 'حجم الفريق',
    contactMessage: 'ما الذي تحتاجه؟',
    contactSubmit: 'إرسال الطلب',
    contactSending: 'جارٍ الإرسال...',
    contactSuccess: 'شكرًا! تم إرسال طلبك وسنتواصل معك قريبًا.',
    contactError: 'تعذر إرسال الطلب. حاول مرة أخرى.',
    contactRequired: 'يرجى تعبئة جميع الحقول المطلوبة.',
    badgePopular: '⭐ الأكثر طلبًا',
    starterMissing: ['عدة مدراء', 'تسجيل دخول GPS', 'تصدير جاهز للرواتب'],
    footnote:
      'جميع الأسعار بالجنيه. قبول فوري وفودافون كاش وتحويل بنكي وبطاقات. تجربة ١٤ يومًا دون بطاقة. تفاصيل الباقات تتبع كتالوج خطتكم في المنتج.',
  },
  signup: {
    title: 'ابدأ تجربتك المجانية ١٤ يومًا',
    subtitle: 'بدون بطاقة ائتمان. أنشئ شركتك في أقل من ٢٠ دقيقة.',
    ownerName: 'اسم المالك',
    companyName: 'اسم الشركة',
    workEmail: 'بريد العمل',
    password: 'كلمة المرور',
    phOwner: 'مثال: أحمد محمد',
    phCompany: 'مثال: أكمي للوجستيات',
    phEmail: 'you@company.com',
    phPassword: '٨ أحرف على الأقل',
    submit: 'إنشاء حساب مجاني ←',
    legal: 'بالتسجيل، أنت توافق على شروط الخدمة وسياسة الخصوصية.',
    errOwner: 'اسم المالك مطلوب',
    errCompany: 'اسم الشركة مطلوب',
    errEmail: 'البريد الإلكتروني مطلوب',
    errEmailInvalid: 'أدخل بريدًا إلكترونيًا صالحًا',
    errPassword: 'كلمة المرور مطلوبة',
    errPasswordLen: '٨ أحرف كحد أدنى',
  },
  testimonials: {
    title: 'فرق انتقلت إلى',
    titleAccent: 'Tik.',
    cards: [
      {
        initials: 'خم',
        name: 'خالد منصور',
        role: 'مدير عمليات، القاهرة',
        quote:
          'كنا ندير كل شيء عبر واتساب. Tik أعطانا تنظيمًا بين ليلة وضحاها. الآن أرى في شاشة واحدة ماذا يعمل فريقي ومن سجّل حضوره.',
      },
      {
        initials: 'نه',
        name: 'نور حسن',
        role: 'مديرة موارد بشرية، الإسكندرية',
        quote:
          'تصدير الحضور وفر على الموارد البشرية ٣ ساعات شهريًا. لا مزيد من Excel اليدوي. المحاسب راضٍ عن التنسيق الجاهز للرواتب.',
      },
      {
        initials: 'سع',
        name: 'سارة عبد الهادي',
        role: 'مديرة تنفيذية، وكالة رقمية',
        quote:
          'مع ٤٠ شخصًا في مكتبين، احتجنا مكانًا واحدًا. تم إعداد Tik في بعد الظهر، والفريق اعتمده فورًا.',
      },
    ],
  },
  cta: {
    title: 'جاهز لإيقاف',
    titleAccent: 'الفوضى؟',
    description:
      'انضم إلى فرق مصر والمنطقة التي استبدلت الأدوات المتفرقة بمركز عمليات واحد — تذاكر، دردشة، وحضور متزامن.',
    primary: 'ابدأ التجربة المجانية — دون بطاقة ←',
    secondary: 'عرض الأسعار',
    footnote: 'تجربة ١٤ يومًا · كل الوحدات الثلاث · إعداد في ٢٠ دقيقة · ويب وموبايل',
  },
  footer: {
    blurb:
      'تذاكر، دردشة الفريق، والحضور — منصة واحدة للشركات الصغيرة والمتوسطة في مصر والمنطقة. استبدل الأدوات المتفرقة بمصدر واحد للحقيقة.',
    product: 'المنتج',
    company: 'الشركة',
    support: 'الدعم',
    linkFeatures: 'الميزات',
    linkPricing: 'الأسعار',
    linkMobile: 'تطبيق الجوال',
    linkChangelog: 'سجل التغييرات',
    linkAbout: 'من نحن',
    linkBlog: 'المدونة',
    linkCareers: 'الوظائف',
    linkContact: 'تواصل',
    linkHelp: 'مركز المساعدة',
    linkOnboarding: 'دليل الإعداد',
    linkStatus: 'حالة النظام',
    linkApi: 'وثائق API',
    rights: 'جميع الحقوق محفوظة.',
    contactEmail: 'tik@absai.dev',
    contactPhone: '01099112703',
    contactAddress: 'القاهرة التجمع الاول وبنفسج 11 و فيلا 55',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة',
    cookies: 'سياسة ملفات تعريف الارتباط',
  },
  trusted: {
    prefix: 'يثق بنا فرق في',
    items: [
      'وكالات تسويق',
      'شركات تقنية',
      'شركات لوجستيات',
      'عيادات خاصة',
      'مكاتب محاماة',
      'عقارات',
      'تجارة إلكترونية',
      'إنشاءات',
      'مصانع',
      'مستشفيات',
    ],
  },
};

export const landingCopy: Record<LandingLang, LandingMessages> = {
  en,
  ar,
};
